# docker-compose.yml para servicios de Backend

services:
  # 1. Base de Datos
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: northernchile_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend en MODO DESARROLLO
  backend:
    image: maven:3.9-eclipse-temurin-21-alpine
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DEVTOOLS_REMOTE_SECRET=tu-secreto-aqui
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_FULL_NAME=${ADMIN_FULL_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_USERS_CONFIG=${ADMIN_USERS_CONFIG}
      - SEED_DATA=${SEED_DATA}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

volumes:
  postgres_data:
  maven_cache:
